---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-actions-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kubernetes-actions-role
rules:
  # Core API
  - apiGroups: [""]
    resources: ["services", "pods", "deployments", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Apps API
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "jobs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Tekton API
  - apiGroups: ["tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-actions-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-actions-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-actions-role
  apiGroup: rbac.authorization.k8s.io